name: aesdatabase
description: A starting point for Dart libraries or applications.
version: 2.1.0
homepage: https://github.com/MahmoudKhalid
repository: https://github.com/MahmoudKhalid/aesdatabase-dart
issue_tracker: https://github.com/MahmoudKhalid/aesdatabase-dart/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  path: ^1.8.2
  aescrypto:
    git:
      url: https://github.com/MahmoudKhalid/aescrypto-dart.git
      ref: main

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.7
